spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      name: config_server
      server:
        git:
          uri: git@github.com:Jaswine/spring-cloud-config.git
          username:
          password:
